config/routes.rb
Rails.application.routes.draw do
  get 'group_pieces/create'

  get 'search/get_instruments_for_group'

  resources :pieces

  resources :groups

  resources :group_pieces

  resources :requests

  resources :users, only: [:show, :edit, :create, :update, :destroy, :index]
  get 'login', to: 'static_pages#login'
  get 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/about', to: 'static_pages#about'

  post 'search/get_instruments_for_group', to: 'search#get_instruments_for_group'

  post '/users/send_email', to: 'users#send_email'

  root 'static_pages#login'

end

app/models/group.rb
class Group < ActiveRecord::Base
  extend Geocoder::Model::ActiveRecord

  belongs_to :instrumentation
  has_many :requests
  has_many :users, through: :requests
  has_many :group_pieces
  has_many :pieces, through: :group_pieces
  belongs_to :admin, class_name: "User"
  has_many :instruments, through: :instrumentation
  geocoded_by :zipcode
  after_validation :geocode
  before_destroy :destroy_requests


  def members
  	requests.where(finalized: true).collect {|request| User.find(request.user_id)}
  end

  def member_ids
  	requests.where(finalized: true).collect {|request| request.user_id}
  end

  def custom_type=(custom_type)
    self.instrumentation = Instrumentation.create(name: "Custom: #{custom_type}")
  end

  def instrument_ids=(attributes)
    attributes.each do |id|
      if !id.empty?
        self.instrumentation.instruments << Instrument.find(id)
      end
    end
    self.instrumentation.save
  end

  def city_state
    result = Geocoder.search(zipcode)
    if result[0]
      "#{result[0].city}, #{result[0].state_code}"
    else
      "Not given"
    end
  end

  private
  def destroy_requests
    requests.destroy_all
  end


end

app/models/instrumentation.rb
class Instrumentation < ActiveRecord::Base
	has_many :groups
	has_many :interests
	has_many :pieces
  has_many :instrument_instrumentations
  has_many :instruments, through: :instrument_instrumentations
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authentication_required, only: [:new, :edit, :create, :update, :destroy]

  def index
    @groups = Group.near(current_user, 20, :order => "distance")
    @full_groups = Group.all
    @users = User.all
    @all_groups = Group.near(current_user, 10000, :order => "distance")
  end

  def show
    @admin = User.find(@group.admin.id)
    if current_user
      @request = Request.find_open_request_by_user_and_group(current_user, @group)
    end
  end

  def new
    @group = Group.new
    @unique_instrumentations = Instrumentation.all[0..15]
  end

  def edit
    @unique_instrumentations = Instrumentation.all[0..15]
    if current_user == @group.admin
      render 'edit'
    else
      redirect_to @group, notice: 'You do not have editing rights for this group'
    end
  end

  def create

    if group_params["instrumentation_id"]=="16"
      @group = Group.new
      @group.custom_type = params[:custom_type]
      @group.save
      @admin = User.find(params[:group][:admin_id])
      @group.zipcode = @admin.zipcode
      @group.name = group_params[:name]
      @group.admin_id = group_params[:admin_id]
      @group.instrument_ids = group_params[:instrument_ids]
    else
      @group = Group.new(group_params)
      @admin = User.find(params[:group][:admin_id])
      @group.zipcode = @admin.zipcode
    end



    respond_to do |format|
      if @group.save
        @request = Request.create(user_id: current_user.id, group_id: @group.id, user_approved: true, group_approved: true, finalized: true)
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_user == @group.admin
      @group.destroy
      respond_to do |format|
        format.html { redirect_to groups_url }
        format.json { head :no_content }
      end
    else
      redirect_to @group, notice: 'You do not have editing rights for this group'
    end
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :instrumentation_id, :complete, :admin_id, :leave, :instrument_ids => [])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_all_matches_table.html.erb
 <table class="table table-hover" id="pricing-table">
  <thead class="header">
    <tr >
      <th>Name</th>
      <th>Type</th>
      <th>Complete</th>
      <% if current_user %>
      <th>Location</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% full_groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group %></td>
        <td class="group_instrumentation"><%= group.instrumentation.name %></td>
        <td class="group_complete"><%= group.complete ? "complete" : "incomplete" %></td>
        <% if current_user && current_user.city_state != "Not given" && group.city_state != "Not given" %>
        <td class="distance"><%= "#{group.admin.city_state} (#{group.distance_from(current_user).round(2)} miles)" if group.zipcode %></td>
        <% else %>
          <td class="distance"> </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/_form.html.erb
  <%= form_for(@group) do |f| %>
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
        <% @group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :instrumentation_id %><br>
      <%= f.collection_select :instrumentation_id, @unique_instrumentations, :id, :name, {prompt: ""}, { class: 'chosen-select', id: 'alternate_instrumentation' } %>

    </div>

    <div class="instrument_options_for_alternate_group">
      <%= label_tag :custom_type, "Ensemble Type" %>
      <%= text_field_tag :custom_type %>
      <%= f.label :instrument_ids, "Instruments" %>
      <%= f.collection_select :instrument_ids, Instrument.all, :id, :name, {prompt: ""}, { class: 'chosen-select', multiple: true} %>
    </div>

    <% if @group.id %>
      <div class="field">
        <%= f.label :complete %><br>
        <%= f.check_box :complete %>
      </div>
    <% end %>

    <div class="field">
      <%= f.hidden_field :admin_id, :value => current_user.id %>
    </div>
    <div class="actions">
      <%= f.submit class: "btn" %>
    </div>
  <% end %>

app/views/groups/_group_info.html.erb
<p>
  <div class= "group_parts">
    <strong>Ensemble Type:</strong>
      <%= group.instrumentation.name %> <a class="show_parts_button">(Show Parts)</a>
      <div class= "show_parts">
        <% group.instrumentation.instrument_instrumentations.each do |i| %>
          <li><%= i.instrument.name %><%= " (x" + i.quantity.to_s + ")" if i.quantity > 1 %> </li>
        <% end %>
      </div>
  </div>
</p>

  <p>
    <strong>Complete:</strong>
    <%= group.complete ? 'yes' : 'no' %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= group.admin.city_state %>
  </p>

  <p>
    <strong>Members:</strong>
    <% group.members.each do |member| %>
      <li><%= link_to member.full_name, member %>, <%= member.instrument.name %></li>
    <% end %>
  </p>
  <p>
    <strong>Admin:</strong>
    <%= link_to admin.full_name, admin %>
  </p>

app/views/groups/_intelligent_matches_table.html.erb
<table class="table table-hover" id="pricing-table">
  <thead class="header">
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Complete</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
    <% groups.where(complete: false).where.not(admin_id: current_user.id).each do |group| %>
      <% current_user.interests.each do |interest| %>
        <% if interest.instrumentation == group.instrumentation %>
        <tr>
          <td><%= link_to group.name, group %></td>
          <td><%= group.instrumentation.name %></td>
          <td><%= group.complete ? "complete" : "incomplete" %></td>
          <% if current_user && current_user.city_state != "Not given" && group.city_state != "Not given" %>
          <td class="distance"><%= "#{group.admin.city_state} (#{group.distance_from(current_user).round(2)} miles)" if (group.zipcode && current_user) %></td>
          <% else %>
          <td class="distance"> </td>
          <% end %>
        </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/groups/_notifications.html.erb
<% if current_user %>
  <% if request %>
    <%= "You have applied to join #{group.name}! Your request is pending :)" if request.group_approved == nil && request.finalized == nil %>
    <% if request.invited? %>
      <%= form_for request do |f| %>
        <%= f.hidden_field :user_approved, value: true %>
        <%= f.submit "Accept Invitation", class: "btn" %>
      <% end %>
      <%= form_for request do |f| %>
        <%= f.hidden_field :user_approved, value: false %>
        <%= f.submit "Deny Invitation", class: "btn"%>
      <% end %>
    <% end %>

  <% elsif !(group.member_ids.include? current_user.id) %>
    <p>Would you like to ask to join <%= group.name %>?</p>
    <%= form_for Request.new do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :user_approved, value: true %>
      <%= f.hidden_field :group_id, value: group.id %>
      <%= f.hidden_field :part, value: current_user.instrument %>
      <%= f.submit "Ask to Join #{group.name}", class: "btn" %>
    <% end %>
  <% end %>
<% end %>

<% if current_user && group.members.include?(current_user) && (current_user != group.admin) %>
  <%= form_for Request.find_by(user: current_user, group: group, finalized: true) do |f| %>
    <%= f.hidden_field :finalized, value: false %>
    <%= f.hidden_field :user_approved, value: false %>
    <%= f.submit 'Leave Group', class: "btn" %>
  <% end %>
<% end %>

app/views/groups/_pieces.html.erb
<strong>Pieces:</strong>
  <% if group.pieces.count==0 %>
  <p>
    <em><%=group.name%> doesn't have any pieces yet! <%= link_to "Add some here", pieces_path %></em>
  </p>
  <% else group.pieces.count > 0 %>
  <p>
    <% group.pieces.each do |piece| %>
      <li id="<%=GroupPiece.find_by(group_id: group.id, piece_id: piece.id).id%>"><%= "#{piece.name} by #{piece.composer}"%>
      <%= link_to image_tag("close-button-gray.gif"), GroupPiece.find_by(group_id: group.id, piece_id: piece.id), class: "delete_piece_x" if current_user == group.admin %>
     </li>
    <% end %>
  </p>
  <% end %>

app/views/groups/_pieces_iframes.html.erb
<% group.pieces.where.not(spotify_id:nil).limit(3).each do |piece| %>
      <iframe src="https://embed.spotify.com/?uri=<%=piece.spotify_id%>" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>
  <% end %>

app/views/groups/_search_form.html.erb
<%= form_for(Group.new) do |f| %>

  <%= f.label :instrumentation_id %>
  <%= f.collection_select :instrumentation_id, Instrumentation.all, :name, :name, {prompt: ""}, { class: 'chosen-select' }  %>

  <%= f.label :instruments %>
  <%= f.collection_select :instruments, Instrument.all, :name, :name, {prompt: ""}, { class: 'chosen-select' } %>

  <%= f.label :complete %>
  <%= f.collection_select :complete, ["complete", "incomplete"], :to_s, :to_s, {prompt: ""}, { class: 'chosen-select' }  %>

  <%= f.submit "Search", class:"search_button btn" %>
  <button class="clear_fields btn">Clear Fields</button>
<% end %>

app/views/groups/edit.html.erb
<div class="container" id="group_edit_page">

  <div class="page-header">
    <h1>Edit Ensemble</h1>
  </div>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>
</div>

app/views/groups/index.html.erb
<div class="container" id="search_form">
  <div class="wrapper">
    <div class="page-header">
      <h1>
        Ensembles
        <% if current_user %>
        <button class="btn intelligent_ensemble_toggle">Show Intelligent Matches</button>
        <%= link_to 'New Ensemble', new_group_path, class: "btn" %>
        <% end %>
      </h1>
    </div>


    <% if current_user %>
    <div class="intelligent_matches">
      <h4>These chamber groups might be a good fit for you based on your preferences.</h4>
      <%= render 'intelligent_matches_table', groups: @groups %>
    </div>
    <% end %>

    <div class="all_ensemble_matches">
      <h4>All Ensembles</h4>
      <%= render 'search_form' %>
      <%= render 'all_matches_table', full_groups: @full_groups %>
    </div>
  </div>
  <!-- wrapper end -->
    <br>
</div>

app/views/groups/new.html.erb
<div class="container" id="group_edit_page">

  <div class="page-header">
    <h1>New Ensemble</h1>
  </div>

  <%= render 'form' %>

  <%= link_to 'Back', groups_path %>
</div>

app/views/groups/show.html.erb
<div class="container" id="white_div">
  <% if current_user && current_user == @group.admin %>
    <% Request.where(group_id: @group.id, finalized: nil, group_approved: nil).each do |request| %>
      <%= link_to request.apply_message, request.user %>
    <% end %>

  <% end %>

  <div class="page-header">
    <h1><%= @group.name %><small><%= "#{@group.instrumentation.name}" %></small><span id="notice"><%= notice %></span></h1>
  </div>


  <div class="row">

    <div class="user-info member span4">
       <%= render 'group_info', group: @group, admin: @admin %>
    </div>

    <div class="user-info member span4"><p></p>
      <%= render 'pieces', group: @group %>
    </div>

    <div class="user-info member span4">
      <%= render 'notifications', group: @group, request: @request %>
    </div>

  </div>

  <div class="pieces_on_group_show">
    <%= render 'pieces_iframes', group: @group %>
  </div>

<%= link_to 'Edit', edit_group_path(@group) if current_user == @group.admin %> |
<%= link_to 'Back', groups_path %> |
<%= link_to 'Destroy Group', @group, method: :delete, data: {confirm: "Are you sure?"} if current_user == @group.admin %>
</div>