config/routes.rb
Rails.application.routes.draw do
  get 'group_pieces/create'

  get 'search/get_instruments_for_group'

  resources :pieces

  resources :groups

  resources :group_pieces

  resources :requests

  resources :users, only: [:show, :edit, :create, :update, :destroy, :index]
  get 'login', to: 'static_pages#login'
  get 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/about', to: 'static_pages#about'

  post 'search/get_instruments_for_group', to: 'search#get_instruments_for_group'

  post '/users/send_email', to: 'users#send_email'

  root 'static_pages#login'

end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  has_many :instrument_instrumentations
  has_many :instrumentations, through: :instrument_instrumentations
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Geocoder::Model::ActiveRecord

  has_many :requests
  has_many :groups, through: :requests
  has_many :interests
  has_many :instrumentations, through: :interests
  has_many :groups, foreign_key: "admin_id"
  belongs_to :instrument
  before_update :check_for_instrument_and_zipcode
  geocoded_by :zipcode
  after_validation :geocode
  before_update :geocode, :validate_zipcode
  before_destroy :destroy_admin_of

  def notifications
    notifications = []
    if Request.where(user_id: self.id, finalized: nil, user_approved: nil)
      Request.where(user_id: self.id, finalized: nil, user_approved: nil).each do |notification|
        notifications << ["invite", "#{notification.group.name} invited you to join!", notification]
      end
    end
    if Request.where(finalized: nil, group_approved: nil)
      Request.where(finalized: nil, group_approved: nil).each do |notification|
        notifications << ["request","#{notification.user.full_name} has requested to join #{notification.group.name}", notification] if notification.group.admin_id == self.id
      end
    end
    notifications
  end

  def eligible_groups(user)
    all_admins_groups = (self.admin_of - user.member_of)
    correct = []
    Request.where(user_id: user.id, finalized: nil).collect do |row|
      if row.group
        correct << row if row.group.admin_id == self.id
      end
    end
    correct_groups = correct.collect {|request| request.group }
    all_admins_groups - correct_groups
  end

  def already_invited(user)
    all_admins_groups = (self.admin_of - user.member_of)
    correct = []
    Request.where(user_id: user.id, finalized: nil).collect do |row|
      if row.group
        correct << row if row.group.admin_id == self.id
      end
    end
    correct_groups = correct.collect {|request| request.group }
    final = all_admins_groups.collect do |group|
     if correct_groups.include? group
       group.name
     end
    end.compact.join(", ")
    "You invited #{user.first_name} to join #{final}!" if !final.empty?
  end

  def validate_zipcode
    /\A\d{5}(-\d{4})?\z/.match(self.zipcode)
  end

  def instrumentation_ids=(attributes)
    self.interests.destroy_all
    attributes.each do |id|
      if !id.empty?
        Interest.find_or_create_by(user_id: self.id, instrumentation_id: id)
      end
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def member_of
    self.requests.collect do |request|
      request.group if request.finalized
    end.compact
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.image = auth.info.image + "?type=large"
      user.email = auth.info.email
      user.gender = auth.extra.raw_info.gender
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save
      if user.email
        UserMailer.welcome_email(user).deliver if !user.check_for_instrument_and_zipcode
       end
    end
  end

  def check_for_instrument_and_zipcode
    !(instrument.nil? || zipcode.empty? || instrument.name.empty?)
  end

  def admin_of
    self.groups.where(:admin_id => self.id)
  end

  def group_ids_for_admin
    self.groups.where(:admin_id => self.id).collect{|group| group.id}
  end

  def pending_requests(user)
    array = group_ids_for_admin.map do |id|
      Request.where(group_id: id, user_id: user.id, finalized: nil, group_approved: nil)[0]
    end
    array.compact
  end

  def gender_pronoun
    if self.gender == 'female'
      "her"
    else
      "him"
    end
  end

  def musician_intelligent_match
    user_array = User.near(self, 20, :order => "distance").where(available: 'seeking a group').collect do |user|
      self.groups.collect do |group|
        if group.instrumentation.instruments.include?(user.instrument)
          if user.instrumentations.include?(group.instrumentation)
            user
          end
        end
      end
    end
    user_array.flatten.compact.uniq.delete_if{|e| e == self}
  end

  def self.return_admins
    self.all.select{|user|!user.admin_of.empty?}
  end

  def admins_close_by
    self.class.return_admins.near(self, order: "distance")
  end

  def city_state
    result = Geocoder.search(zipcode)
    if result[0]
      "#{result[0].city}, #{result[0].state_code}"
    else
      "Not given"
    end
  end

  private
  def destroy_admin_of
    if admin_of
      admin_of.destroy_all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :registered?, only: [:show, :edit, :update, :create]

  def index
    @all_users = User.near(current_user, 10000, :order => "distance")
    @full_users = User.all
    @instrument_list = Instrument.order(:name)
    @ensemble_types = Instrumentation.order(:name)
  end

  def show
  end

  def send_email
    @recipient_name = params[:recipient_name]
    @recipient_email = params[:recipient_email]
    @sender_name = params[:sender_name]
    @sender_email = params[:sender_email]
    @content = params[:content]
    UserMailer.contact_user(@sender_name, @sender_email, @recipient_name, @recipient_email, @content).deliver
    redirect_to User.find_by(email: @recipient_email)
  end

  def edit
    @instrument_list = Instrument.order(:name)
    @ensemble_types = Instrumentation.all
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Profile was successfully updated' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { redirect_to @user, notice: 'Please include instrument and zipcode :)' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :instrument_id, :gender, :first_name, :last_name, :short_bio, :image, :email, :zipcode, :instrument, :level, :video_sample, :audio_sample, :phone_number, :available, :instrumentation_ids => [])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_accept_deny.html.erb
<% if (current_user && current_user.pending_requests(user).size > 0 && user != current_user) %>
     <p>Accept <%= user.first_name %>'s request?</p>
     <p><% current_user.pending_requests(user).each do |request| %>
          <%= form_for request do |f| %>
            <%= f.hidden_field :group_approved, value: true %>
            <%= f.submit "Accept Request to join #{request.group.name}", class: "btn" %>
          <% end %>
          <%= form_for request do |f| %>
            <%= f.hidden_field :group_approved, value: false %>
            <%= f.submit "Deny Request to join #{request.group.name}", class: "btn" %>
          <% end %>
        <%end%>
      </p>
  <% end %>

app/views/users/_all_matches_table.html.erb
<table class="table table-hover" id="pricing-table">
  <thead class="header">
    <tr>
      <th>Name</th>
      <th>Instrument</th>
      <th>Level</th>
      <th>Interests</th>
      <th>Availability</th>
      <% if current_user %>
      <th>Location</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% full_users.each do |user| %>
      <% if user.check_for_instrument_and_zipcode %>
        <tr>
          <td class="name_field"><%= link_to user.full_name, user %></td>
          <td class="instrument_field"><%= user.instrument.name %></td>
          <td class="level_field"><%= user.level %></td>
          <td class="interests_field"><%= user.interests.collect{|i|i.instrumentation.name}.uniq.join(", ") %></td>
          <td class="available_field"><%= user.available %></td>
          <% if current_user && current_user.city_state != "Not given" && user.city_state != "Not given" %>
            <td class="distance"><%= user.city_state %> <br>(<%= user.distance_from(current_user).round(2) %> miles)</td>
          <% else %>
            <td class="distance"> </td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/_contact.html.erb
<% if current_user && current_user != user %>
    <h1 id="email"><small><span class="email_form_button"><%= image_tag "mail.png" %>Contact <%= user.first_name %></span></small></h1>
    <%= form_tag("/users/send_email", method: "post", class: "email_form") do %>
      <%= hidden_field_tag(:sender_name, current_user.full_name) %>
      <%= hidden_field_tag(:sender_email, current_user.email) %>
      <%= hidden_field_tag(:recipient_name, user.full_name) %>
      <%= hidden_field_tag(:recipient_email, user.email) %>
      <%= text_area_tag :content %>
      <p><%= submit_tag "Send Message", class: "btn", id: "email_button" %></p>
    <% end %>
  <% end %>

app/views/users/_form.html.erb
<div class="container">
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :instrument %><br>
      <%= f.text_field :instrument %>
    </div>
    <div class="field">
      <%= f.label :gender %><br>
      <%= f.text_field :gender %>
    </div>
    <div class="field">
      <%= f.label :short_bio %><br>
      <%= f.text_field :short_bio %>
    </div>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.text_field :image %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :zipcode %><br>
      <%= f.number_field :zipcode %>
    </div>
    <div class="field">
      <%= f.label :phone_number %><br>
      <%= f.text_field :phone_number %>
    </div>
    <div class="field">
      <%= f.label :instrument %><br>
      <%= f.text_field :instrument %>
    </div>
    <div class="field">
      <%= f.label :level %><br>
      <%= f.text_field :level %>
    </div>
    <div class="field">
      <%= f.label :video_sample %><br>
      <%= f.text_field :video_sample %>
    </div>
    <div class="field">
      <%= f.label :audio_sample %><br>
      <%= f.text_field :audio_sample %>
    </div>
    <div class="field">
      <%= f.label :type_preferences %><br>
      <%= f.text_field :type_preferences %>
    </div>
    <div class="field">
      <%= f.label :style_preferences %><br>
      <%= f.text_field :style_preferences %>
    </div>
    <div class="field">
      <%= f.label :availability %><br>
      <%= f.number_field :availability %>
    </div>
    <div class="actions">
      <%= f.submit class:"btn"%>
    </div>
  <% end %>
</div>

app/views/users/_image.html.erb
<p>
  <%= image_tag user.image %>
  <p><%= link_to 'Update Profile', edit_user_path if current_user==user%></p>
</p>

app/views/users/_intelligent_matches_table.html.erb
<table id="pricing-table" class="table table-hover">
  <h4>These musicians might be a good fit for your group based on your preferences.</h4>
  <thead class="header">
    <tr>
      <th>Name</th>
      <th>Instrument</th>
      <th>Level</th>
      <th>Interests</th>
      <th>Availability</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
    <% current_user.musician_intelligent_match.each do |user| %>
      <tr>
        <td><%= link_to user.full_name, user %></td>
        <td><%= user.instrument.name %></td>
        <td><%= user.level %></td>
        <td><%= user.interests.collect{|i|i.instrumentation.name}.join(", ") %></td>
        <td><%= user.available %></td>
        <% if current_user && current_user.city_state != "Not given" && user.city_state != "Not given" %>
          <td class="distance"><%= user.city_state %><br> (<%= user.distance_from(current_user).round(2) %> miles)</td>
        <% else %>
          <td class="distance"> </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_invite.html.erb
<% if (current_user && user != current_user && !current_user.admin_of.empty? && !(current_user.eligible_groups(user)).empty?) %>
    Would you like to invite <%= user.first_name %> to one of your ensembles?

    <%= form_for Request.new do |f| %>
      <p>
      <%= f.collection_select :group_id, current_user.eligible_groups(user), :id, :name %>
      </p>
      <%= f.hidden_field :user_id, value: user.id %>
      <%= f.hidden_field :group_approved, value: true %>
      <%= f.submit "Invite #{user.first_name}", class: "btn" %>
    <% end %>

<% end %>

app/views/users/_main_info.html.erb
<h1><%= user.full_name %><small><%= "#{user.instrument.name}" if user.instrument %></small>
<span id="notice">
  <p><%= notice %></p>
  <% if current_user %>
  <p><%= current_user.already_invited(user) if current_user!=user %></p>
  <% end %>
  <p><%= "Welcome to Ensemblify! Please fill out the rest of your profile!" unless (user.check_for_instrument_and_zipcode || user != current_user) %></p>
</span></h1>

app/views/users/_search_form.html.erb
<%= form_for(User.new) do |f| %>
  <%= f.label :instrument_id %>
  <%= f.collection_select :instrument_id, instrument_list, :name, :name, {prompt: ""}, { class: 'chosen-select' } %>
  <%= f.label :available %>
  <%= f.collection_select :available, ["seeking a group","all set"], :to_s, :to_s, {prompt: ""}, { class: 'chosen-select' } %>
  <%= f.label :instrumentation_ids, "Interests" %>
  <%= f.collection_select :instrumentation_ids, ensemble_types, :name, :name, {prompt: ""}, { class: 'chosen-select' } %>
  <%= f.label :level %>
  <%= f.collection_select :level, ["beginner", "intermediate", "advanced", "professional"], :to_s, :to_s, {prompt: ""}, { class: 'chosen-select' } %>
  <p></p>
  <div class="search_and_clear">
    <%= f.submit "Search", class:"search_button btn" %>
    <button class="clear_fields btn">Clear Fields</button>
  </div>
<% end %>

app/views/users/_user_ensembles.html.erb
 <% if !user.member_of.empty? %>
    <strong>Ensembles:</strong>
  <% user.member_of.each do |group| %>
    <li><%= link_to group.name, group %></li>
  <% end %>
<% else %>
  <strong>Ensembles:</strong>
  <% if current_user == user && current_user.check_for_instrument_and_zipcode %>
    <br>You are not currently a member of any ensembles.<br><%= link_to 'Check some out', groups_path%> or <%= link_to 'create your own', new_group_path %>?
  <% elsif current_user != user && user.groups.empty? %>
    <%= "#{user.first_name} isn't in any ensembles." %>
  <% end %>
<% end %>

app/views/users/_user_info_2.html.erb
<p><strong>Video Sample: </strong><%= link_to user.video_sample, user.video_sample, target: "blank" if !user.video_sample.empty? %></p>
  <p><strong>Audio Sample: </strong><%= link_to user.audio_sample, user.audio_sample, target: "blank" if !user.audio_sample.empty? %></p>
  <% if user.interests.any? %>
    <strong>Ensemble Preferences:</strong>
    <ul>
    <% user.interests.each do |interest| %>
      <li><%= interest.instrumentation.name %></li>
    <% end %>
    </ul>
  <% end %>

app/views/users/edit.html.erb
<div class="container" id="white_div">
    <div class="page-header">
      <h1>Update your profile</h1>
    </div>

    <div class="row">
      <div class="update-user-left member span4">
        <%= form_for(@user) do |f| %>
          <p>
          <%= f.label :instrument_id %><span style="color: red">*</span><br>
          <%= f.collection_select :instrument_id, @instrument_list, :id, :name, {prompt: "< select >"}, {required: true, class: 'chosen-select' } %>
          </p>
          <p>
          <%= f.label :level %><br>
          <%= f.collection_select :level, ["beginner", "intermediate", "advanced", "professional"], :to_s, :to_s, {prompt: "< select >"}, { class: 'chosen-select' } %>
          </p>
          <p>
          <%= f.label :zipcode %><span style="color: red">*</span><br>
          <%= f.text_field :zipcode, required: true, class: "zipcode_field" %>
          </p>
<!--           <p>
          <%#= f.label :phone_number %><br>
          <%#= f.telephone_field :phone_number %>
          </p> -->
          <p>
          <%= f.label :available %><br>
          <%= f.collection_select :available, ["seeking a group", "all set"], :to_s, :to_s, {prompt: "< select >"}, { class: 'chosen-select' } %>
          </p>
        </div>

        <div class="update-user-right member span4">
          <p>
          <%= f.label :short_bio %><br>
          <%= f.text_area :short_bio %>
          </p>
          <p>
          <%= f.label :video_sample %><br>
          <%= f.text_field :video_sample, placeholder: "https://www.youtube.com/example" %>
          </p>
          <p>
          <%= f.label :audio_sample %><br>
          <%= f.text_field :audio_sample, placeholder: "https://soundcloud.com/example" %>
          </p>
          <br>
        </div>
        <div class="update-user-right member span4">
          <p>
          <%= f.label :instrumentation_ids, "Ensemble Preferences:" %><br>
          <%= f.collection_select :instrumentation_ids, @ensemble_types, :id, :name, {prompt: ""}, { class: 'chosen-select', id: "make_wider", multiple: true} %>
          </p>
            <p>
            <%= f.submit "Save Settings", class: "btn edit_form", id: "settings_edit_button" %><%= link_to "Cancel", @user, class: "btn" %>
            </p>
        </div>
        <% end %>

    </div>

</div>

app/views/users/index.html.erb
<div class="container" id="search_form">

  <div class="wrapper">

    <div class="page-header">
      <h1>
        Musicians
        <% if current_user %>
        <button class="btn intelligent_musician_toggle">Show Intelligent Matches</button>
        <% end %>
      </h1>
    </div>

    <% if current_user %>
      <div class="intelligent_matches">
        <%= render 'intelligent_matches_table' %>
      </div>
    <% end %>

    <div class="all_matches">
      <h4>Showing all musicians</h4>
      <%= render 'search_form', instrument_list: @instrument_list, ensemble_types: @ensemble_types %>
      <%= render 'all_matches_table', full_users: @full_users %>
    </div>

  </div>

</div>

app/views/users/show.html.erb
<div class="container" id="white_div">

  <% if current_user == @user %>
    <% Request.where(user_id: @user.id, finalized: nil, user_approved: nil).each do |request| %>
    <%= link_to request.invite_message, request.group %><br>
    <% end %>
  <% end %>

  <div class="page-header">
    <%= render 'main_info', user: @user %>
  </div>

  <div class="row">

    <div class="user-image member span3">
      <%= render 'image', user: @user %>
    </div>

    <div class="user-info member span3">
      <%= render 'user_info_1', user: @user %>
    </div>

    <div class="user-info member span3">
      <%= render 'user_info_2', user: @user %>
    </div>

    <div class="member-of-ensembles member span2"> <!-- both  -->
       <%= render 'user_ensembles', user: @user %>
    </div>

  </div>

  <div class="row">

    <div class="like-to-invite member span4"> <!-- only for other viewing user -->
      <%= render 'invite', user: @user %>
    </div>


    <div class="accept-deny-buttons member span4"> <!-- only for other viewing user -->
      <%= render 'accept_deny', user: @user %>
    </div>

    <div class="email_area member span4"> <!-- only for other viewing user -->
        <%= render 'contact', user: @user %>
    </div>

  </div>

</div>