config/routes.rb
Rails.application.routes.draw do
  get 'group_pieces/create'

  get 'search/get_instruments_for_group'

  resources :pieces

  resources :groups

  resources :group_pieces

  resources :requests

  resources :users, only: [:show, :edit, :create, :update, :destroy, :index]
  get 'login', to: 'static_pages#login'
  get 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/about', to: 'static_pages#about'

  post 'search/get_instruments_for_group', to: 'search#get_instruments_for_group'

  post '/users/send_email', to: 'users#send_email'

  root 'static_pages#login'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Ensemblify</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
      <%= stylesheet_link_tag    'application', media: 'all' %>
      <%= javascript_include_tag 'application' %>
      <%= csrf_meta_tags %>
      <%= analytics_init if Rails.env.production? %>
    <!-- favicon -->
    <link rel="shortcut icon" href="treble_clef_small">
    <link href='http://fonts.googleapis.com/css?family=Niconne' rel='stylesheet' type='text/css'>
  </head>


  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/groups"><%= image_tag "treble_clef_small.png" %>ensemblify</a>
          <div class="nav-collapse">
            <ul class="nav pull-right">
              <% if current_user %>
              <% requests = current_user.notifications %>
                <% if requests && requests.size > 0 %>
                <li>
                  <div id="notification">
                    <%= requests.size %>
                  </div>
                </li>
                <div id= "notifications_triangle">
                </div>
                <div id="notifications_box">
                <div id="notification_label">Notifications (<%= requests.size %>)</div>
                <% requests.each do |request| %>
                  <div class="individual_notification">
                    <% if request[0] == "invite" %>
                      <%= link_to request[1], group_path(request[2].group), class: "individual_link" %>
                    <% else %>
                      <%= link_to request[1], user_path(request[2].user), class: "individual_link" %>
                    <% end %>
                  </div>
                <% end %>
                </div>
                <% end %>
              <% end %>
              <li>
                <%= link_to "#{current_user.full_name}", current_user if logged_in? %>
              </li>
              <li><%= link_to "Musicians", users_path %></li>
              <li><%= link_to "Ensembles", groups_path  %></li>
              <li><%= link_to "Pieces", pieces_path  %></li>
              <li><%= link_to "About", about_path  %></li>
              <li><%= link_to "Login", "/login" unless logged_in?%></li>
              <li><%= link_to "Logout", "/logout" if logged_in? %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>


    <%= yield %>

    <footer class="white navbar-fixed-bottom">
      Made by <%= link_to "Catherine Meyers", "http://www.github.com/ccmeyers", target: "blank" %>, <%= link_to "Rebecca Greenblatt", "http://www.github.com/rebeccagreenblatt", target: "blank" %>, and <%= link_to "Will Lowry", "http://www.github.com/wlowry88", target: "blank" %> at <%= link_to "The Flatiron School", "http://flatironschool.com/", target: "blank" %>
    </footer>

  </body>
</html>